name: ci

on: 
  release: 
    types: [published]

jobs: 
  publish-lib:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: zip
        run: zip -r $(basename $(pwd)).zip lib include

      - name: publish
        uses: softprops/action-gh-release@v1
        with:
          tag_name: stm32f103rb-max7219-lib-v1.0.0
          files: *.zip 